<a href="https://colab.research.google.com/github/AbhiVidholiya7026/Codveda_Internship_projects/blob/Level3/L3T2_NLP_TextClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Level 3 - Task 2**

##**Natural Language Processing (NLP) - Text Classification**

Dataset: Sentiment dataset.csv

Goal:
Classify text into positive or negative sentiment.

### **Importing Libraries**

In [14]:
import pandas as pd
import nltk
import string

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

### **Load Dataset**

In [16]:
df = pd.read_csv("Sentiment dataset.csv")

df.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

### **Text preprocessing**

We remove punctuation, stopwords, and apply stemming

In [17]:
stop_words = set(stopwords.words('english'))

stemmer = PorterStemmer()

def preprocess(text):

    text = text.lower()

    text = text.translate(str.maketrans('', '', string.punctuation))

    words = text.split()

    words = [stemmer.stem(word) for word in words if word not in stop_words]

    return " ".join(words)

df["clean_text"] = df["Text"].apply(preprocess)

df.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,clean_text
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12,enjoy beauti day park
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8,traffic terribl morn
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15,finish amaz workout 💪
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18,excit upcom weekend getaway
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19,tri new recip dinner tonight

### **Convert Text to Numerical features**

Machine Learning models require Numbers

We use TF-IDF vectorization.

In [18]:
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["clean_text"])

y = df["Sentiment"]

### **Train-Test Split**

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

### **Train Classification Model**

In [20]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

### **Predictions**

In [21]:
y_pred = model.predict(X_test)

### **Evaluate Model**

In [22]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

Accuracy: 0.08843537414965986
                        precision    recall  f1-score   support

         Acceptance          0.00      0.00      0.00         2
           Admiration        0.00      0.00      0.00         1
        Admiration           0.00      0.00      0.00         1
         Affection           0.00      0.00      0.00         1
      Ambivalence            0.00      0.00      0.00         1
         Anger               0.00      0.00      0.00         1
        Anticipation         0.00      0.00      0.00         1
        Arousal              0.00      0.00      0.00         3
                  Awe        0.00      0.00      0.00         1
         Awe                 0.00      0.00      0.00         1
                  Bad        0.00      0.00      0.00         1
             Betrayal        0.00      0.00      0.00         2
        Betrayal             0.00      0.00      0.00         1
         Bitter              0.00      0.00      0.00         1
           Bitterness        0.00      0.00      0.00         1
          Bittersweet        0.00      0.00      0.00         1
              Boredom        0.00      0.00      0.00         1
         Calmness            0.00      0.00      0.00         1
          Captivation        0.00      0.00      0.00         1
     Celestial Wonder        0.00      0.00      0.00         1
             Colorful        0.00      0.00      0.00         1
      Confusion              0.00      0.00      0.00         3
           Connection        0.00      0.00      0.00         1
        Contemplation        0.00      0.00      0.00         1
          Contentment        0.00      0.00      0.00         3
        Contentment          0.00      0.00      0.00         1
         Coziness            0.00      0.00      0.00         1
         Creativity          0.00      0.00      0.00         1
            Curiosity        0.00      0.00      0.00         2
          Curiosity          0.00      0.00      0.00         1
      Curiosity              0.00      0.00      0.00         2
           Desolation        0.00      0.00      0.00         1
           Devastated        0.00      0.00      0.00         2
              Disgust        0.00      0.00      0.00         1
         Disgust             0.00      0.00      0.00         2
        Elation              0.00      0.00      0.00         3
             Elegance        0.00      0.00      0.00         1
          Embarrassed        0.00      0.00      0.00         1
       EmotionalStorm        0.00      0.00      0.00         1
        Empowerment          0.00      0.00      0.00         1
         Enjoyment           0.00      0.00      0.00         2
           Enthusiasm        0.00      0.00      0.00         1
              Envious        0.00      0.00      0.00         2
  Envisioning History        0.00      0.00      0.00         1
         Euphoria            0.00      0.00      0.00         1
           Excitement        0.05      0.33      0.09         3
         Excitement          0.00      0.00      0.00         3
        Excitement           0.00      0.00      0.00         1
         Fear                0.00      0.00      0.00         1
              Fearful        0.00      0.00      0.00         1
           Frustrated        0.00      0.00      0.00         1
          Frustration        0.00      0.00      0.00         3
         Fulfillment         0.00      0.00      0.00         2
             Grateful        0.00      0.00      0.00         1
      Grief                  0.00      0.00      0.00         1
                Happy        0.00      0.00      0.00         6
                 Hate        0.00      0.00      0.00         2
           Heartbreak        0.00      0.00      0.00         2
              Hopeful        1.00      1.00      1.00         1
        InnerJourney         0.00      0.00      0.00         1
        Inspiration          0.00      0.00      0.00         1
             Inspired        0.00      0.00      0.00         1
            Isolation        0.00      0.00      0.00         1
          Jealousy           0.00      0.00      0.00         1
                  Joy        0.11      0.75      0.19         8
         Joy                 0.00      0.00      0.00         1
        JoyfulReunion        0.00      0.00      0.00         1
         Kind                0.00      0.00      0.00         1
           Loneliness        1.00      1.00      1.00         1
      Loneliness             0.00      0.00      0.00         1
             LostLove        0.00      0.00      0.00         1
      Melancholy             0.00      0.00      0.00         2
       Miscalculation        0.00      0.00      0.00         1
              Neutral        0.00      0.00      0.00         1
        Nostalgia            0.00      0.00      0.00         1
      Nostalgia              0.00      0.00      0.00         1
      Numbness               0.00      0.00      0.00         1
          Overwhelmed        0.00      0.00      0.00         1
              Playful        0.00      0.00      0.00         2
            Positive         0.06      0.44      0.10         9
                Proud        0.00      0.00      0.00         1
        Reflection           0.00      0.00      0.00         1
       Regret                0.00      0.00      0.00         1
           Resilience        0.00      0.00      0.00         1
            Reverence        0.00      0.00      0.00         1
         Sadness             0.00      0.00      0.00         2
        Satisfaction         0.00      0.00      0.00         1
             Serenity        0.00      0.00      0.00         2
      Serenity               0.00      0.00      0.00         2
             Solitude        0.00      0.00      0.00         1
          Sorrow             0.00      0.00      0.00         1
         Spark               0.00      0.00      0.00         1
         Surprise            0.00      0.00      0.00         1
        Thrill               0.00      0.00      0.00         1
             Vibrancy        0.00      0.00      0.00         1
 Whispers of the Past        0.00      0.00      0.00         1
                 Zest        0.00      0.00      0.00         1

              accuracy                           0.09       147
             macro avg       0.02      0.04      0.02       147
          weighted avg       0.02      0.09      0.03       147

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## **Report :**

The sentiment analysis model classifies text into positive and negative categories. Text preprocessing techniques including tokenization, stopword removal, and stemming were applied. TF-IDF vectorization converted text into numerical features. A Logistic Regression classifier achieved good performance with high accuracy and balanced precision and recall.